name: Kreator Backend Services Deployment
on:
  push:
      branches:
        - kreatorbackendservices
env:
  APPLICATION_PROPERTIES: ${{ secrets.KREATORBACKENDSERVICES_APPLICATION_PROPERTIES }}
  HEROKU_API_KEY: ${{ secrets.KREATORBACKENDSERVICES_HEROKU_API_KEY }}
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8 
      - name: Set up application properties
        run: echo -e $APPLICATION_PROPERTIES > src/main/resources/application.properties && cat src/main/resources/application.properties
      - name: MVN Clean Install
        run:  mvn clean install
      - name: Move Build files
        run:  mkdir build && mv target/kreatorRestServices.war build/ && mv target/dependency/webapp-runner.jar build/ && mv Procfile build/
      - uses: actions/upload-artifact@master
        with:
          name: build-files
          path: build/

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: build-files
          path: build/
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Install dpl
        run: gem install dpl
      - name: Deploy to heroku
        run: cd build && dpl --provider=heroku --app=${GITHUB_REF#refs/heads/} --api-key=${{ env.HEROKU_API_KEY }} --skip_cleanup